name: Bridge
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  get:
  get_storage:
  firebase_auth:
  google_sign_in:
  firebase_core:
  cupertino_icons:
  font_awesome_flutter:
  connectivity: ^0.4.9
  device_preview:
  cached_network_image:
  material_design_icons_flutter: 
  # remove and add own timeago 
  timeago:
  flare_splash_screen:
  shimmer_animation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  lint:
  effective_dart:
  flutter_launcher_icons: "^0.7.5"
  flutter_launcher_name: "^0.0.1" 

flutter_launcher_name:
  name: "Bridge"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon/Bridge_Icon.png"
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appIcon/
    - assets/png/
    - assets/splash/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
