// Login API's
class Api {
  //Anonymous User Section...
  //Anonymous Feeds in Home Page...
  static const anonymousHome =
      'https://us-central1-bridge-fd58f.cloudfunctions.net/anonymous/home';

  //Auth Section...
  //User Register...
  static const userRegister =
      'https://us-central1-bridge-fd58f.cloudfunctions.net/auth/register';
  //User Login...
  static const userLogin =
      'https://us-central1-bridge-fd58f.cloudfunctions.net/auth/login';
  //User Logout...
  static const userLogout =
      'https://us-central1-bridge-fd58f.cloudfunctions.net/auth/logout';
}