class Api {
  //Auth Section...
  //User Register...
  static const register =
      'https://us-central1-bridge-fd58f.cloudfunctions.net/auth/register';
  //User Login...
  static const login =
      'https://us-central1-bridge-fd58f.cloudfunctions.net/auth/login';
  //User Logout...
  static const logout =
      'https://us-central1-bridge-fd58f.cloudfunctions.net/auth/logout';
}
